# Setup
title:        Philo
tagline:      A Philosophy Blog
baseurl:      ""
paginate:     1
locale:       "en"
bg: blur.jpg

# About/contact
author:
  name:       Chris Varga
  url:        https://github.com/chrisvarga

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
